### ISSUE TITLE
Ubuntu 19 libtinfo needed

### ISSUE THREAD

**Issue by bmann** [fission-suite/cli#42]
Reported in [Discord](https://discordapp.com/channels/478735028319158273/635952875050369034/644909844498743306)

> I was trying to get the fission cli working on Ubuntu 19.10 last night. I kept getting "error while loading shared libraries: libtinfo.so.5" Installing libtinfo-dev didn't seem to help.

**Comment by bmann** [comment]
Did some searching. Ubuntu 19 ships with libtinfo.so.6 and reportedly Haskell has trouble on that system:

https://github.com/spacchetti/spago/issues/104#issuecomment-462179206

**Comment by expede** [comment]
We now have reports that it's building fine on Ubuntu 19.10. The problem is not an issue with _Haskell_ and libtinfo.so.6, but that the version we're releasing is built with libtinfo.so.5. We need to add a newer Linux to the build pipeline. This is the same as the linked `spago` issue, which is being built in an Ubuntu 16 Docker container.

**Comment by expede** [comment]
Superseded by #45
