### ISSUE TITLE
Reading vs Writing the .fission.yaml file

### ISSUE THREAD

**Issue by MCTaylor17** [fission-suite/cli#56]
# Summary
Theres a mismatch between two related functions in `/library/Fission/CLI/Environment.hs`.

## Problem
When authenticating, `findLocalAuth` performs a recursive search for `.fission.yaml` starting in `getCurrentDirectory`
When logging in or registering, `globalEnv` points directly to `getHomeDirectory`

### Impact
The `.fission.yaml` file can be written to a different location than where it can be found resulting in an error message that can't be corrected without manual intervention.

## Solution
Consider authenticating directly from `globalEnv`.

# Detail

For Windows WSL users, the config file always writes to the Linux file system (either `/root/.fission.yaml` or `/home/<user>/.fission.yaml` depending on factors) even though the authentication expects it in `/mnt/c/Users/<user>/.fission.yaml`.

**To Reproduce**
1. Open command prompt from somewhere in Windows user documents
2. `wsl fission login` -> username, password
3. `wsl fission whoami`

Results: `Unable to read credentials. Try logging in with fission-cli login`

**Expected behavior**
Login credentials stored in the same place they are searched for.

**Screenshots**

**Desktop:**
 - OS: Windows 10 with Windows Subsystem for Linux
 - Version: Fission 1.22.0

**Additional context**
This would make writing installation guide much much simpler.

**Comment by dholms** [comment]
Hey @MCTaylor17 thanks for filing this, and the detailed report!

We don't want to authenticate directly from `globalEnv` because users can have multiple accounts. For instance, I might use one username globally, but another username for a specific project. If I keep a `.fission.yaml` in that project's root, then all actions from within that project will be authenticated with the local auth.

On Linux & macOS, recursing up the filesystem eventually comes to the user's home directory. Unfortunately WSL does this differently :stuck_out_tongue: 

We still want local project-specific auth to work. So what we can do is search recursively for auth, if that comes up short, then default to `globalEnv`.

**Comment by MCTaylor17** [comment]
Ahhhh, I see now.  I had trouble reading the Haskel but I understand your logic.  I used something similar on one of my own projects (I called it the "Process Hop" based on Super Mario).

> then default to globalEnv.

Yeah, a fallback would do the trick.  The fix could be made on the write side as well.  Either use the current directory or hop up to the highest Castle...

**Comment by dholms** [comment]
Yup exactly!

I made a PR to fix this issue: https://github.com/fission-suite/cli/pull/57

_Note:_ I tested these by doing `fission whoami` at a location that does not recurse through my home dir (`/`). I can't test on WSL without doing some heavy setup first. Would you mind giving this a quick go to make sure that it works as intended?

Are you able to build the binary yourself, or should we build & distribute it to you?
